### ISSUE TITLE
sed: couldn't open file

### ISSUE THREAD

**Issue by thomas-merz** [aguther/nmonchart#1]
Hi,

I'm using nmonchart via a hourly cronjob which executes:
/usr/local/bin/nmonchart.cron; service nmon restart >/dev/null 2>&1; sleep 1m; rsync -arz -v --delete -o -p /var/log/nmon/ /shared/sys/nmondata/`uname -n`/ >/dev/null 2>&1

Occasionally I got errors for the rest of the day:
sed: couldn't open file /tmp/nmonchart.sed.15901*: No such file or directory
rm: cannot remove `/tmp/nmonchart.sed.15901*': No such file or directory

Please help and fix it.

Thanks a lot in advance
Thomas

**Comment by thomas-merz** [comment]
Wrote an E-Mail to Nigel R. Griffiths, the original author of nmonchart.

**Comment by ladams00** [comment]
I could be mistaken, but I had a similar issue with trying to process the topasrec binary collections converted via topasout.  The date field substitution string in nmonchart is case sensitive, and the topasout case is different from nmon.  That may be enough of a hint for you or Nigel to work around it :-)
